RECUPERACION/EXAMEN/4_Mayo_Symfony_Javier_Alvarez/src/Entity/Solicitante.php
<?php

namespace App\Entity;

use App\Repository\SolicitanteRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SolicitanteRepository::class)]
class Solicitante
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nombre = null;

    #[ORM\Column(length: 9)]
    private ?string $dni = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTime $fecha_nac = null;

    #[ORM\Column]
    private ?int $nomina = null;

    #[ORM\Column]
    private ?bool $concedida = null;

    #[ORM\ManyToOne(inversedBy: 'solicitantes')]
    private ?Beca $beca = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): static
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getDni(): ?string
    {
        return $this->dni;
    }

    public function setDni(string $dni): static
    {
        $this->dni = $dni;

        return $this;
    }

    public function getFechaNac(): ?\DateTime
    {
        return $this->fecha_nac;
    }

    public function setFechaNac(\DateTime $fecha_nac): static
    {
        $this->fecha_nac = $fecha_nac;

        return $this;
    }

    public function getNomina(): ?int
    {
        return $this->nomina;
    }

    public function setNomina(int $nomina): static
    {
        $this->nomina = $nomina;

        return $this;
    }

    public function isConcedida(): ?bool
    {
        return $this->concedida;
    }

    public function setConcedida(bool $concedida): static
    {
        $this->concedida = $concedida;

        return $this;
    }

    public function getBeca(): ?Beca
    {
        return $this->beca;
    }

    public function setBeca(?Beca $beca): static
    {
        $this->beca = $beca;

        return $this;
    }
}

RECUPERACION/EXAMEN/4_Mayo_Symfony_Javier_Alvarez/src/Form/SolicitanteForm.php
<?php

namespace App\Form;

use App\Entity\Beca;
use App\Entity\Solicitante;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SolicitanteForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nombre')
            ->add('dni')
            ->add('fecha_nac')
            ->add('nomina')
            ->add('concedida')
            ->add('beca', EntityType::class, [
                'class' => Beca::class,
                'choice_label' => 'descripcion',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Solicitante::class,
        ]);
    }
}

RECUPERACION/EXAMEN/4_Mayo_Symfony_Javier_Alvarez/src/Controller/SolicitanteController.php
<?php

namespace App\Controller;

use App\Entity\Solicitante;
use App\Form\SolicitanteForm;
use App\Repository\SolicitanteRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/solicitante')]
final class SolicitanteController extends AbstractController
{
    #[Route(name: 'app_solicitante_index', methods: ['GET'])]
    public function index(SolicitanteRepository $solicitanteRepository): Response
    {
        return $this->render('solicitante/index.html.twig', [
            'solicitantes' => $solicitanteRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_solicitante_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $solicitante = new Solicitante();
        $form = $this->createForm(SolicitanteForm::class, $solicitante);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($solicitante);
            $entityManager->flush();

            return $this->redirectToRoute('app_solicitante_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('solicitante/new.html.twig', [
            'solicitante' => $solicitante,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_solicitante_show', methods: ['GET'])]
    public function show(Solicitante $solicitante): Response
    {
        return $this->render('solicitante/show.html.twig', [
            'solicitante' => $solicitante,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_solicitante_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Solicitante $solicitante, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(SolicitanteForm::class, $solicitante);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_solicitante_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('solicitante/edit.html.twig', [
            'solicitante' => $solicitante,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_solicitante_delete', methods: ['POST'])]
    public function delete(Request $request, Solicitante $solicitante, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$solicitante->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($solicitante);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_solicitante_index', [], Response::HTTP_SEE_OTHER);
    }
}

RECUPERACION/EXAMEN/4_Mayo_Symfony_Javier_Alvarez/templates/solicitante/_delete_form.html.twig
<form method="post" action="{{ path('app_solicitante_delete', {'id': solicitante.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ solicitante.id) }}">
    <button class="btn">Delete</button>
</form>

RECUPERACION/EXAMEN/4_Mayo_Symfony_Javier_Alvarez/templates/solicitante/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

RECUPERACION/EXAMEN/4_Mayo_Symfony_Javier_Alvarez/templates/solicitante/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Solicitante{% endblock %}

{% block body %}
    <h1>Edit Solicitante</h1>

    {{ include('solicitante/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_solicitante_index') }}">back to list</a>

    {{ include('solicitante/_delete_form.html.twig') }}
{% endblock %}

RECUPERACION/EXAMEN/4_Mayo_Symfony_Javier_Alvarez/templates/solicitante/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Solicitante index{% endblock %}

{% block body %}
    <h1>Solicitante index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Dni</th>
                <th>Fecha_nac</th>
                <th>Nomina</th>
                <th>Concedida</th>
                <th>Tipo de beca</th>
                <th>cantidad</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for solicitante in solicitantes %}
            <tr>
                <td>{{ solicitante.id }}</td>
                <td>{{ solicitante.nombre }}</td>
                <td>{{ solicitante.dni }}</td>
                <td>{{ solicitante.fechaNac ? solicitante.fechaNac|date('Y-m-d') : '' }}</td>
                <td>{{ solicitante.nomina }}</td>
                <td>{{ solicitante.concedida ? 'Sí' : 'No' }}</td>
                <td>{{ solicitante.beca.descripcion }}</td>
                <td>{{ solicitante.beca.cantidad }}</td>
                <td>
                    <a href="{{ path('app_solicitante_show', {'id': solicitante.id}) }}">show</a>
                    <a href="{{ path('app_solicitante_edit', {'id': solicitante.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_solicitante_new') }}">Create new</a>
{% endblock %}

RECUPERACION/EXAMEN/4_Mayo_Symfony_Javier_Alvarez/templates/solicitante/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Solicitante{% endblock %}

{% block body %}
    <h1>Create new Solicitante</h1>

    {{ include('solicitante/_form.html.twig') }}

    <a href="{{ path('app_solicitante_index') }}">back to list</a>
{% endblock %}

RECUPERACION/EXAMEN/4_Mayo_Symfony_Javier_Alvarez/templates/solicitante/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Solicitante{% endblock %}

{% block body %}
    <h1>Solicitante</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ solicitante.id }}</td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td>{{ solicitante.nombre }}</td>
            </tr>
            <tr>
                <th>Dni</th>
                <td>{{ solicitante.dni }}</td>
            </tr>
            <tr>
                <th>Fecha_nac</th>
                <td>{{ solicitante.fechaNac ? solicitante.fechaNac|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Nomina</th>
                <td>{{ solicitante.nomina }}</td>
            </tr>
            <tr>
                <th>Concedida</th>
                <td>{{ solicitante.concedida ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_solicitante_index') }}">back to list</a>

    <a href="{{ path('app_solicitante_edit', {'id': solicitante.id}) }}">edit</a>

    {{ include('solicitante/_delete_form.html.twig') }}
{% endblock %}